from __future__ import annotations

import json
import os


def _seed_inicial() -> list[dict]:
    """The tenant's REAL history if it exists on disk (e.g. data-demo/
    audit.json, regenerated by data-demo/generar.py on every boot), used
    ONLY to seed Postgres the first time (once per tenant). With no file,
    there's nothing to seed — a brand-new tenant starts with an empty log
    (it's append-only, no _SEED-style fallback)."""
    from core import paths
    archivo = os.path.join(paths.DATA_DIR, "audit.json")
    if not os.path.exists(archivo):
        return []
    try:
        return json.load(open(archivo, encoding="utf-8"))
    except Exception:
        return []


class AuditLog:
    """Registro append-only de toda acción sobre los datos: quién, qué,
    antes y después. Es la trazabilidad que sostiene la confianza."""

    def __init__(self, base_dir: str | None = None):
        # base_dir is unused now (Postgres, not JSON) — kept as a parameter
        # so existing call sites (core/store.py, etc.) don't need to change.
        pass

    def record(self, actor: str, accion: str, antes=None, despues=None) -> dict:
        from core.db import audit_repo, tenant as _tenant
        tid = _tenant.current_tenant_id()
        audit_repo.seed_if_empty(tid, _seed_inicial())
        return audit_repo.record(tid, actor=actor, action=accion, before=antes, after=despues)

    def list(self) -> list[dict]:
        from core.db import audit_repo, tenant as _tenant
        tid = _tenant.current_tenant_id()
        audit_repo.seed_if_empty(tid, _seed_inicial())
        return audit_repo.list_events(tid)
