"""
Organización (tenant) — la base multi-tenant.

Cada PyME es una organización con su config y sus usuarios. Hoy Horizonte es
el tenant único, pero la estructura está lista para sumar un segundo sin tocar
la lógica: los datos y la config viven por organización.

Distinción de scope (clave del producto):
  - config de ORGANIZACIÓN (margen mínimo, balanzas por peso): la fija el dueño,
    afecta a todos los usuarios del tenant. Scope "organization".
  - personalización de VISTA (gráficos, columnas): la hace cada usuario para sí.
    Scope "user" (vive en su memoria, no acá).
"""
from __future__ import annotations

import json
import os

from . import paths

HERE = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = paths.DATA_DIR  # por-tenant: env POLPILOT_DATA_DIR o data/ (ver core/paths.py)
ORG_JSON = os.path.join(DATA_DIR, "organizacion.json")

DEFAULT = {
    "id": "piloto",
    "nombre": "Supermercados Horizonte",
    "rubro": "distribuidora + supermercado + franquicias",
    "config": {
        "margen_minimo": 30,        # %; Ángela alerta lo que esté por debajo
        "balanza_por_peso": True,   # los productos de balanza se computan por kg
    },
}

# Cambios que afectan a TODA la organización → requieren rol dueño/admin.
CLAVES_ORG = {"margen_minimo", "balanza_por_peso"}


def _seed_inicial() -> dict:
    """The tenant's REAL config if it exists on disk (e.g. data-demo/
    organizacion.json, regenerated by generar.py on every boot), used ONLY
    to seed Postgres the first time (once per tenant). DEFAULT is the
    fallback for a tenant with no config of its own yet (the test "piloto"
    tenant) — see core/db/MIGRATING_A_MODULE.md."""
    try:
        return {**DEFAULT, **json.load(open(ORG_JSON, encoding="utf-8"))}
    except Exception:
        return dict(DEFAULT)


def get() -> dict:
    from core.db import organization_repo, tenant as _tenant
    tid = _tenant.current_tenant_id()
    org = organization_repo.get_config(tid)
    if org is None:
        org = _seed_inicial()
        organization_repo.save_config(tid, org)
    return org


def set_config(clave: str, valor) -> dict:
    from core.db import organization_repo, tenant as _tenant
    org = get()
    org["config"][clave] = valor
    organization_repo.save_config(_tenant.current_tenant_id(), org)
    return org


def puede_config_org(rol: str | None) -> bool:
    """Sólo el dueño (o admin delegado) cambia config de organización."""
    return (rol or "").strip().lower() in ("dueño", "dueno", "admin")
