// Stable query keys for every cached REST read. Prefix matching does
// invalidation: `['polpilot', 'inventario']` also refreshes viz / top / burn.

const ROOT = "polpilot";

export const keys = {
  all: () => [ROOT],
  paged: () => [ROOT, "paged"],

  health: () => [ROOT, "health"],
  actividad: () => [ROOT, "actividad"],
  inicio: () => [ROOT, "inicio"],
  equipoNombres: () => [ROOT, "equipo", "nombres"],
  onboarding: () => [ROOT, "onboarding"],
  objetivos: () => [ROOT, "objetivos"],
  objetivosMedidos: () => [ROOT, "objetivos-medidos"],
  muestras: () => [ROOT, "muestras"],
  vozMuestras: () => [ROOT, "voz", "muestras"],
  grupo: (nombre, limit) => [ROOT, "grupo", nombre, limit ?? null],
  buscar: (q) => [ROOT, "buscar", q],
  buscarGlobal: (q) => [ROOT, "buscar-global", q],
  fichaProducto: (codigo) => [ROOT, "ficha", "producto", codigo],
  oportunidades: () => [ROOT, "oportunidades"],
  prioridades: () => [ROOT, "prioridades"],
  patronHistorial: () => [ROOT, "patrones", "historial"],
  ordenesPreparadas: () => [ROOT, "ordenes-preparadas"],
  ubicaciones: () => [ROOT, "ubicaciones"],
  proveedores: () => [ROOT, "proveedores"],
  lotes: () => [ROOT, "lotes"],
  productos: (params = {}) => [ROOT, "productos", params],
  sales: (params = {}) => [ROOT, "sales", params],
  receipts: (params = {}) => [ROOT, "receipts", params],
  movimientos: (params = {}) => [ROOT, "movimientos", params],
  conciliacion: () => [ROOT, "conciliacion"],
  margenes: () => [ROOT, "margenes"],
  margenesDetalle: (grupo) => [ROOT, "margenes", grupo],
  cierresLocales: (dias) => [ROOT, "cierres-locales", dias ?? null],
  mostradorCostosViejos: () => [ROOT, "mostrador", "costos-viejos"],
  traslados: () => [ROOT, "traslados"],
  vencimientos: (dias) => [ROOT, "vencimientos", dias ?? null],
  conocimiento: (params = {}) => [ROOT, "conocimiento", params],
  conocimientoPendientes: (nodo) => [ROOT, "conocimiento", "pendientes", nodo ?? null],
  analisis: () => [ROOT, "analisis"],
  reponer: () => [ROOT, "reponer"],
  auditoria: (filters = {}) => [ROOT, "auditoria", filters],
  auditoriaHilo: (sujeto) => [ROOT, "auditoria", "hilo", sujeto],
  autonomia: () => [ROOT, "autonomia"],
  whatsappBotConfig: () => [ROOT, "whatsapp-bot", "config"],
  whatsappBotConversaciones: () => [ROOT, "whatsapp-bot", "conversaciones"],
  whatsappBotMensajes: (conversationId) => [ROOT, "whatsapp-bot", "mensajes", conversationId],
  conectores: () => [ROOT, "conectores"],
  odooConfig: () => [ROOT, "conectores", "odoo"],
  cobranza: () => [ROOT, "cobranza"],
  cobranzaPropuesta: (id) => [ROOT, "cobranza", "propuesta", id],
  grafo: (sinNotas) => [ROOT, "grafo", sinNotas ?? null],
  escenaReclamo: () => [ROOT, "escena", "reclamo"],
  cerebroToolsNodos: () => [ROOT, "cerebro", "tools-nodos"],
  evals: () => [ROOT, "evals"],
  mapaOperacion: () => [ROOT, "mapa-operacion"],
  mapaOperacionNodo: (nid) => [ROOT, "mapa-operacion", "nodo", nid],
  fase: () => [ROOT, "fase"],
  articulos: () => [ROOT, "articulos"],
  imported: () => [ROOT, "imported"],
  inventario: () => [ROOT, "inventario"],
  inventarioTop: (n) => [ROOT, "inventario", "top", n ?? null],
  inventarioViz: () => [ROOT, "inventario", "viz"],
  inventarioBurn: (codigo) => [ROOT, "inventario", "burn", codigo],
  calidad: () => [ROOT, "calidad"],
  anomalias: () => [ROOT, "anomalias"],
  balanzas: () => [ROOT, "balanzas"],
  documento: (tipo) => [ROOT, "documentos", tipo],
  documentosListado: () => [ROOT, "documentos", "listado"],
  carpetaPedidos: () => [ROOT, "carpeta"],
  carpeta: (numero) => [ROOT, "carpeta", numero],
  carpetaDocumento: (numero, docId) => [ROOT, "carpeta", numero, docId],
  cuentas: () => [ROOT, "cuentas"],
  parada: (cliente) => [ROOT, "parada", cliente],
  paradasProximas: (transporte) => [ROOT, "parada", "proximas", transporte ?? null],
  cuentaRecordatorio: (id) => [ROOT, "cuentas", "recordatorio", id],
  recordatorios: () => [ROOT, "recordatorios"],
  equipoActividad: () => [ROOT, "equipo", "actividad"],
  evolucion: () => [ROOT, "evolucion"],
  forecast: () => [ROOT, "forecast"],
  pagos: () => [ROOT, "pagos"],
  macro: () => [ROOT, "macro"],
  deposito: (dias) => [ROOT, "deposito", dias ?? null],
  ventas: () => [ROOT, "ventas"],
  ventasValidacion: () => [ROOT, "ventas", "validacion"],
  caja: () => [ROOT, "caja"],
  syncDelta: (formato) => [ROOT, "sync", "delta", formato ?? null],
  versiones: () => [ROOT, "versiones"],
  saneamientoProponer: (cat) => [ROOT, "saneamiento", "proponer", cat],
  contexto: () => [ROOT, "contexto"],
  staging: () => [ROOT, "staging"],
  stagingPreview: (id) => [ROOT, "staging", "preview", id],
  memoria: (usuario) => [ROOT, "memoria", usuario],
  widgetPlataParada: (dias) => [ROOT, "widget", "plata-parada", dias ?? null],
  consultaSerie: (consulta) => [ROOT, "consulta-serie", consulta],
  preferencias: () => [ROOT, "me", "preferencias"],
  perfil: (usuario) => [ROOT, "perfil", usuario],
  perfiles: () => [ROOT, "perfiles"],
  solicitudes: (estado) => [ROOT, "solicitudes", estado ?? null],
  adminMatriz: () => [ROOT, "admin", "matriz"],
  notificaciones: () => [ROOT, "notificaciones"],

  piso: {
    all: () => [ROOT, "piso"],
    destinatario: (tipo) => [ROOT, "piso", "destinatario", tipo],
    avisosOficio: () => [ROOT, "piso", "avisos-oficio"],
    mios: () => [ROOT, "piso", "mios"],
    reportes: (tipo, estado) => [ROOT, "piso", "reportes", tipo ?? null, estado ?? null],
    propuestas: () => [ROOT, "piso", "propuestas"],
  },
};
