import { queryOptions } from "@tanstack/react-query";
import { api } from "../api";
import { keys } from "./keys";

function q(keyFn, method, extra = {}) {
  return (...args) => queryOptions({
    queryKey: keyFn(...args),
    queryFn: () => {
      const fn = typeof method === "string" ? api[method] : method;
      return fn(...args);
    },
    ...extra,
  });
}

export const queries = {
  health: q(keys.health, "health", { staleTime: 5 * 60_000 }),
  actividad: q(keys.actividad, "actividad"),
  inicio: q(keys.inicio, "inicio"),
  equipoNombres: q(keys.equipoNombres, "equipoNombres"),
  onboarding: q(keys.onboarding, "onboarding"),
  objetivos: q(keys.objetivos, "objetivos"),
  objetivosMedidos: (token) => queryOptions({
    queryKey: keys.objetivosMedidos(),
    queryFn: () => api.objetivosMedidos(token),
  }),
  muestras: q(keys.muestras, "muestras"),
  vozMuestras: q(keys.vozMuestras, "vozMuestras"),
  grupo: q(keys.grupo, "grupo"),
  buscar: q(keys.buscar, "buscar"),
  buscarGlobal: q(keys.buscarGlobal, "buscarGlobal"),
  fichaProducto: q(keys.fichaProducto, "fichaProducto"),
  oportunidades: q(keys.oportunidades, "oportunidades"),
  prioridades: q(keys.prioridades, "prioridades"),
  patronHistorial: q(keys.patronHistorial, "patronHistorial"),
  ordenesPreparadas: q(keys.ordenesPreparadas, "ordenesPreparadas"),
  ubicaciones: q(keys.ubicaciones, "ubicaciones"),
  proveedores: q(keys.proveedores, "proveedores"),
  lotes: q(keys.lotes, "lotes"),
  productos: q(keys.productos, "productos"),
  sales: q(keys.sales, "sales"),
  receipts: q(keys.receipts, "receipts"),
  movimientos: q(keys.movimientos, "movimientos"),
  conciliacion: q(keys.conciliacion, "conciliacion"),
  margenes: q(keys.margenes, "margenes"),
  margenesDetalle: q(keys.margenesDetalle, (...a) => api.margenes_detalle(...a)),
  cierresLocales: q(keys.cierresLocales, "cierresLocales"),
  mostradorCostosViejos: q(keys.mostradorCostosViejos, "mostradorCostosViejos"),
  traslados: q(keys.traslados, "traslados"),
  vencimientos: q(keys.vencimientos, "vencimientos"),
  conocimiento: q(keys.conocimiento, "conocimiento"),
  conocimientoPendientes: q(keys.conocimientoPendientes, "conocimientoPendientes"),
  analisis: q(keys.analisis, "analisis"),
  reponer: q(keys.reponer, "reponer"),
  auditoria: q(keys.auditoria, "auditoria"),
  auditoriaHilo: q(keys.auditoriaHilo, "auditoriaHilo"),
  autonomia: q(keys.autonomia, "autonomia"),
  whatsappBotConfig: q(keys.whatsappBotConfig, "whatsappBotConfig"),
  whatsappBotConversaciones: q(keys.whatsappBotConversaciones, "whatsappBotConversaciones"),
  whatsappBotMensajes: q(keys.whatsappBotMensajes, "whatsappBotMensajes"),
  conectores: q(keys.conectores, "conectores"),
  odooConfig: q(keys.odooConfig, "odooConfig"),
  cobranza: q(keys.cobranza, "cobranza"),
  cobranzaPropuesta: q(keys.cobranzaPropuesta, "cobranzaPropuesta"),
  grafo: q(keys.grafo, "grafo"),
  escenaReclamo: q(keys.escenaReclamo, "escenaReclamo"),
  cerebroToolsNodos: q(keys.cerebroToolsNodos, "cerebroToolsNodos"),
  evals: q(keys.evals, "evals"),
  mapaOperacion: q(keys.mapaOperacion, "mapaOperacion"),
  mapaOperacionNodo: q(keys.mapaOperacionNodo, "mapaOperacionNodo"),
  fase: q(keys.fase, "fase"),
  articulos: q(keys.articulos, "articulos"),
  imported: q(keys.imported, "imported"),
  inventario: q(keys.inventario, "inventario"),
  inventarioTop: q(keys.inventarioTop, "inventarioTop"),
  inventarioViz: q(keys.inventarioViz, "inventarioViz"),
  inventarioBurn: q(keys.inventarioBurn, "inventarioBurn"),
  calidad: q(keys.calidad, "calidad"),
  anomalias: q(keys.anomalias, "anomalias"),
  balanzas: q(keys.balanzas, "balanzas"),
  documento: q(keys.documento, "documento"),
  documentosListado: q(keys.documentosListado, "documentosListado"),
  carpetaPedidos: q(keys.carpetaPedidos, "carpetaPedidos"),
  carpeta: q(keys.carpeta, "carpeta"),
  carpetaDocumento: q(keys.carpetaDocumento, "carpetaDocumento"),
  cuentas: q(keys.cuentas, "cuentas"),
  parada: q(keys.parada, "parada"),
  paradasProximas: q(keys.paradasProximas, "paradasProximas"),
  cuentaRecordatorio: q(keys.cuentaRecordatorio, "cuentaRecordatorio"),
  recordatorios: q(keys.recordatorios, "recordatorios"),
  equipoActividad: q(keys.equipoActividad, "equipoActividad"),
  evolucion: q(keys.evolucion, "evolucion"),
  forecast: q(keys.forecast, "forecast"),
  pagos: q(keys.pagos, "pagos"),
  macro: q(keys.macro, "macro"),
  deposito: q(keys.deposito, "deposito"),
  ventas: q(keys.ventas, "ventas"),
  ventasValidacion: q(keys.ventasValidacion, "ventasValidacion"),
  caja: q(keys.caja, "cajaEstado"),
  syncDelta: q(keys.syncDelta, "syncDelta"),
  versiones: q(keys.versiones, "versiones"),
  saneamientoProponer: q(keys.saneamientoProponer, "saneamientoProponer"),
  contexto: q(keys.contexto, "contextoListar"),
  staging: q(keys.staging, "stagingListar"),
  stagingPreview: q(keys.stagingPreview, "stagingPreview"),
  memoria: q(keys.memoria, "memoria"),
  widgetPlataParada: q(keys.widgetPlataParada, "widgetPlataParada"),
  consultaSerie: q(keys.consultaSerie, "consultaSerie"),
  preferencias: q(keys.preferencias, "preferencias"),
  perfil: q(keys.perfil, "perfil"),
  perfiles: (token) => queryOptions({
    queryKey: keys.perfiles(),
    queryFn: () => api.perfiles(token),
  }),
  solicitudes: (token, estado) => queryOptions({
    queryKey: keys.solicitudes(estado),
    queryFn: () => api.solicitudes(token, estado),
  }),
  adminMatriz: (token) => queryOptions({
    queryKey: keys.adminMatriz(),
    queryFn: () => api.adminMatriz(token),
  }),
  notificaciones: (token) => queryOptions({
    queryKey: keys.notificaciones(),
    queryFn: () => api.notificaciones(token),
  }),
  pisoDestinatario: q(keys.piso.destinatario, (...a) => api.piso.destinatario(...a)),
  pisoAvisosOficio: q(keys.piso.avisosOficio, (...a) => api.piso.avisosOficio(...a)),
  pisoMios: q(keys.piso.mios, (...a) => api.piso.mios(...a)),
  pisoReportes: q(keys.piso.reportes, (...a) => api.piso.reportes(...a)),
  pisoPropuestas: q(keys.piso.propuestas, (...a) => api.piso.propuestas(...a)),
};
